---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: dataset-110474
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 0
      start_hour = 1
      end_hour = 23
      blacklisted_namespaces = ["apollo","default","elastic-system","ingress","kube-node-lease","kube-public","kube-system"]
      whitelisted_namespaces = [ "dataset-110474", "test-kill-namespace" ]
      time_zone = "Africa/Abidjan"
      graceperiod_sec= 10
