---

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-monkey-config-map
      namespace: dataset-110474
    data:
      config.toml: |
        [kubemonkey]
        run_hour = 0
        start_hour = 1
        end_hour = 23
        blacklisted_namespaces = ["apollo","default","elastic-system","ingress","kube-node-lease","kube-public","kube-system"]
        whitelisted_namespaces = [ "dataset-110474", "test-kill-namespace" ]
        time_zone = "Australia/Melbourne"
        graceperiod_sec= 10
        [notifications]
          enabled = true
          reportSchedule = true
          [notifications.attacks]
            endpoint = "test1"
            message = '''{"foo":"bar","bar":"foo"}'''
            headers = ["header1Key:header1Value", "header2Key:header2Value" ]
