apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: chaos-monkey
  namespace: dataset-110474
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-monkey
subjects:
- kind: ServiceAccount
  name: default
  namespace: dataset-110474
